### ISSUE TITLE
I was trying to start the front-end but I was a bit confused with the instructions to do it

### ISSUE THREAD

**Issue by raulvillora** [bq/bitbloq-frontend#62]
Hi.

I was trying to start the front-end but I was a bit confused with the instructions to do it.

I am not sure where I can find the information to fill the clientId field or how it should be filled at the facebook.json

I have the same question for the clientId and apikey fields at the google.json

I will appreciate any information.

Thanks so much,

Raul.

**Comment by tocalvo** [comment]
Hi, sorry about the lack of documentation, you need to add config files in json format.

You have to add a config file with the enviroment data, please put it on the app/res/config folder. 
The file must a json format like this:

{
    "env": "local",
    "defaultLang": "es-ES",
    "supportedLanguages": [
        "es-ES",
        "en-GB",
        "nl-NL",
        "ru-RU",
        "it-IT",
        "eu-ES",
        "ca-ES",
        "fr-FR",
        "de-DE",
        "pt-PT",
        "gl",
        "zh-CN"
    ],
    "saveTime": 2000,
    "serverUrl_": "http://localhost:8000/bitbloq/v1/",
    "gCloudUrl": "",
    "compilerUrl": "http://localhost:3000/",
    "bucket": "",
    "chromeAppId": "nlndpbeidnfnjpfkmlcakphlbilpokho",
    "web2boardLinkWindows": "https://github.com/bq/web2board/releases/download/Latest/windows_web2board_installer.exe",
    "web2boardLinkMac": "https://github.com/bq/web2board/releases/download/Latest/mac_web2board_installer.pkg",
    "web2boardLinkLinux": "https://github.com/bq/web2board/releases/download/Latest/linux_64_web2board_installer.zip",
    "web2boardLinkLinux32": "https://github.com/bq/web2board/releases/download/Latest/linux_32_web2board_installer.zip",
    "version": "v3.3.6"
}

To allow facebook and google login, you have to include this files in the same folder 

facebook.json with this content:

{
    "clientId": "yourID",
    "scope": [
        "public_profile",
        "email"
    ],
    "status": false,
    "xfbml": false,
    "display": "popup",
    "popupOptions": {
        "width": 500,
        "height": 500
    }
}

And a google.json with this content:

{
    "clientId": "Your clientId",
    "apikey": "Your Api Key",
    "scope": [
        "https://www.googleapis.com/auth/plus.login",
        "https://www.googleapis.com/auth/plus.me",
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile",
        "https://www.googleapis.com/auth/urlshortener",
        "https://www.googleapis.com/auth/drive.file"
    ],
    "apis": [{
        "name": "plus",
        "version": "v1"
    }],
    "visibleActions": "http://schemas.google.com/AddActivity",
    "responseType": "token",
    "display": "popup",
    "popupOptions": {
        "width": 580,
        "height": 400
    }
}

Just with the creation is enough to start the front, if you want to add support to social login, just fill the fields clientId and api key.

**Comment by raulvillora** [comment]
Thank you so much for information.

I obtained the following error, maybe you could help me:

>> Local Npm module "grunt-sass" not found. Is it installed?

Running "serve" task

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "generateConstantsFileWithConfig" task

Running "ngconstant:local" (ngconstant) task
Creating module config at app/res/config/config.js...OK

Running "wiredep:app" (wiredep) task
Warning: Error: Cannot find where you keep your Bower packages. Use --force to continue.

Aborted due to warnings.

**Comment by raulvillora** [comment]
I solved it!

This command solve the problems which are related with npm modules:

sudo  npm install --unsafe-perm && bower install --unsafe-perm
