### ISSUE TITLE
Issues when running the local server

### ISSUE THREAD

**Issue by raulvillora** [bq/bitbloq-frontend#63]
Hi I've read the documentation that you've posted about he frontend and how to run it.

After doing the whole process, I've ran the project using grunt serve and I've found the following issues:

jquery.jspanel.js:39 Loaded: jQuery 2.1.1, jQuery UI 1.12.1
UI core: true, UI widget: true, UI mouse: true, UI draggable: true, UI resizable: true
jquery.jspanel.js:1422 jsPanel version: 2.6.2 2016-03-18 08:17
angular.js:12221 Array(1)
(anonymous) @ angular.js:12221
angular.js:12221 Bitbloq version: v3.9.0
:9000/undefineduser/me Failed to load resource: the server responded with a status of 404 (Not Found)
angular.js:12221 TypeError: Cannot read property 'length' of undefined
    at X (angular-google-analytics.min.js:9)
    at angular-google-analytics.min.js:9
    at V (angular-google-analytics.min.js:9)
    at Object._trackPage (angular-google-analytics.min.js:9)
    at angular-google-analytics.min.js:9
    at Scope.$broadcast (angular.js:16038)
    at angular-route.js:619
    at processQueue (angular.js:14454)
    at angular.js:14470
    at Scope.$eval (angular.js:15719)
(anonymous) @ angular.js:12221
:9000/undefinedhardware Failed to load resource: the server responded with a status of 404 (Not Found)
:9000/images/avatar/ Failed to load resource: the server responded with a status of 404 (Not Found)
:9000/undefinedhardware Failed to load resource: the server responded with a status of 404 (Not Found)
angular.js:12221 sortToolbox
:9000/undefinedproperty Failed to load resource: the server responded with a status of 404 (Not Found)
:9000/undefinedbloq?page=0&pageSize=90 Failed to load resource: the server responded with a status of 404 (Not Found)
:9000/images/project/ Failed to load resource: the server responded with a status of 404 (Not Found)

------------------------------------------------------------------------------------------------------

Thank you so much for your time.

I will appreciate any information related with it.

Raul.

**Comment by tocalvo** [comment]
Hi! You need to launch the bitbloq backend to handle the frontend request, you can found it here:
https://github.com/bq/bitbloq-backend (git clone, run the "npm install" command in the folder) You need a mongo db database too, in the local.
