### ISSUE TITLE
Question: Which of the following blocks would you recommend to a project that will use Blockly features: the ones you are using in BitBloq or the blocks of Blockly ?

### ISSUE THREAD

**Issue by raulvillora** [bq/bitbloq-frontend#77]
Good morning,

We've forked your project cause we're pretty interested in the structure you are using.

We were wondering if you may help us with the following decision:

**Which of the following blocks would you recommend to a project that will use Blockly features: the ones you are using in BitBloq or the blocks of Blockly ?**

Thank you so much,

We will appreciate any answer related with the topic,

We wish you have wonderful day.

**Comment by tocalvo** [comment]
Hi! :wave:
Both libraries can help you, bloqs is the Bitbloq library you can find here: https://github.com/bq/bloqs .

Last time i check blocky was year ago, so maybe this opinion is wrong right now, take it carefully and i always recommend test it by yourself ;)

If you need html blocks or drag and drop them between html items in your interface, you should  use Bitbloq bloqs library (or another similar library, but i don't know another, this is why we create bloqs few years ago). If you don't need it and can integrate well with canvas use blockly, blocky  have too much support and people dedicated to them, so any bug you found will be fixed sooner, supports mobile browsers and have better documentation.

Cheers! :-)
